# -*- coding: utf-8 -*-
"""projetoebac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wBT7Y7CmDCUa6d2gHNOjS_QB-315Uwl
"""

def calculadora():
    print("Calculadora")
    print("Opções: +, -, *, /")

    while True:
        try:
            nome_de_usuario = input("Digite seu nome: ")
            print("Olá,", nome_de_usuario)
            num1 = float(input("Digite o primeiro número: "))
            operacao = input("Digite a operação: ")
            num2 = float(input("Digite o segundo número: "))

            if operacao == "+":
                resultado = num1 + num2
                print("O Resultado da soma é:", resultado)
            elif operacao == "-":
                resultado = num1 - num2
                print("O Resultado da subtração é:", resultado)
            elif operacao == "*":
                resultado = num1 * num2
                print("O Resultado da multiplicação é:", resultado)
            elif operacao == "/":
                if num2 == 0:
                    print("Erro: Divisão por zero.")
                    continue
                resultado = num1 / num2
                print("O Resultado da divisão é:", resultado)
            else:
                print("Operação inválida.")
            break  # Sai do loop após o cálculo
        except ValueError:
            print("Entrada inválida. Certifique-se de digitar números e uma operação válida.")

calculadora()

